export const UPDATE_USER = "UPDATE_USER";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const UPDATE_MODEL_INFO = "UPDATE_MODEL_INFO";
export const UPDATE_MODEL_NAME = "UPDATE_MODEL_NAME";
export const UPDATE_LEARNING_RATE = "UPDATE_LEARNING_RATE";
export const UPDATE_EPOCH = "UPDATE_EPOCH";

export const UPDATE_TASK_ID = "UPDATE_TASK_ID";
export const SET_CSV_PATH = "SET_CSV_PATH";
export const SET_SELECTED_FILE = "SET_SELECTED_FILE";
export const SET_LOG_INFO = "SET_LOG_INFO";
export const SET_READY_TO_UPLOAD = "SET_READY_TO_UPLOAD";
export const SET_MODEL_LOCATION = "SET_MODEL_LOCATION";
export const SET_DOWNLOAD_URL = "SET_DOWNLOAD_URL";
export const SET_DOWNLOAD_DEFAULT = "SET_DOWNLOAD_DEFAULT";
export const SET_OUTPUT_FILE_NAME = "SET_OUTPUT_FILE_NAME";